sudo: required
dist: trusty
branches:
  only:
  - gcs
language: php
php:
  - '5.5.9'
  - hhvm
  - nightly

notifications:
  email:
    recipients:
      - viny-pinheiro@gmail.com
    on_success: always
